name: PR-CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and run Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q

    - name: Create Retail Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@master
      with:
        name: kgPanels-PR-${{ github.head_ref }}
        path: .release/

    - name: Create Classic Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g 1.13.2 -m .pkgmeta-classic
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@master
      with:
        name: kgPanels-PR-${{ github.head_ref }}-classic
        path: .release/
