name: PR-CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -qo '011'"
        annotate: warning

    - name: Create Package
      uses: BigWigsMods/packager@v2
      with:
        args: -d -z

    - uses: actions/upload-artifact@v3
      with:
        name: kgPanels-PR#${{ github.event.number }}-${{ github.sha }}
        path: .release
